from random import randint


products_body = [
    {
        "id": 67,
        "title": "DANESON BOOZE & MINT TOOTHPICKS",
        "description": "Mint and cinnamon mint toothpicks are joined bourbon and single malt flavors in this four-pack set. $32.",
        "detailed_description": "They say variety is the spice of life, and it's also the reason d'être for Daneson's Every Blend pack. Included are warm and spicy Cinna Mint toothpicks, their Mint No.9 toothpicks, with a mix of cooling sweet ingredients, and both their Single Malt and Bourbon toothpicks. The latter start out as wood-forward before the intricacies of the spirits start to emerge. Great for after dinner or anytime a burst of flavor is desired, they come in a gift box with four bottles of 12 toothpicks each.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 32,
        "preview_img_id": 67,
    },
    {
        "id": 68,
        "title": "WAYNE ENTERPRISES X UNCRATE X PATRICKS GROOMING COLLECTION",
        "description": "Patricks takes their already industry-leading grooming tech to the next level, exclusively for Wayne Enterprises and Uncrate. $60+.",
        "detailed_description": "Patricks is already known for being on the cutting-edge of men's grooming technology, which is exactly why they were tapped as the exclusive grooming launch partner for the Wayne Enterprises x Uncrate collection. Included in the custom-developed, three-piece grooming regimen is the WE1 Natural Deodorant, WE2 Anti-Fatigue Moisturizer, and WE3 Eye Serum. Each is formulated with all natural, bleeding-edge ingredients such as Swiss glacier biotechnology, colloidal gold, and for the deodorant Niodor, a future-oriented crystalline powder that is nature-identical to mineral simonkolleite. All are purpose built for those who encounter long nights followed by the need to immediately turn around to fully groomed and an awakened appearance at a moment's notice.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 60,
        "preview_img_id": 68,
    },
    {
        "id": 69,
        "title": "JACK HENRY BALANCE COLOGNE",
        "description": "Fragrance balances optimism, tranquility, and vitality with a blend of amber, cedarwood, and bergamot. $125.",
        "detailed_description": "Finding your balance takes time. For Jack Henry, it took four years of development. The Balance fragrance was carefully formulated in-house and combines organic ingredients to evoke a sense of optimism, tranquility, and vitality. It blends a base of amber, patchouli, and musk with heart notes of cedarwood, jasmine, and vetiver, topped with bergamot, mandarin, and aqua resulting in an intriguing aroma that evolves throughout the day. Bottled in southern California, the scent is cruelty-free, vegan, and non-toxic and is housed in sustainable and fully-recycled packaging. Balance is currently available for pre-order with shipping on December 15, 2022.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 12,
        "preview_img_id": 69,
    },
    {
        "id": 70,
        "title": "QUIP ORAL CARE PRODUCTS",
        "description": "An Uncrate-only bundle of Tooletries' bathroom grooming and organizing essentials. $65.",
        "detailed_description": "Uncrate has assembled Tooletries Ultimate Shower Set. The exclusive selection of the brand's grooming and organizing tools includes bathroom essentials to enhance the efficiency of your morning routine. To keep you clean, it comes with the Body Scrubber & Hook, an antimicrobial silicone deep-cleaning exfoliating body scrubber with a rust-free, waterproof storage hook, while the Scalp Massager & Hook controls flakes and boosts blood flow for stronger, thicker hair. The Mason Razor Holder offers a dedicated space to store your trusted shaving go-to, and The Archer Magnet Mount keeps tweezers, clippers, and scissors in one place. Each item is easy to attach to any smooth surface in your bathroom using Tooletries patent silicone-grip technology.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 65,
        "preview_img_id": 70,
    },
    {
        "id": 71,
        "title": "TOOLETRIES ULTIMATE SHOWER SET",
        "description": "Keep valuables, cash, or any other small items safe from prying eyes with this portable safe. $249.",
        "detailed_description": "Whether it's valuables, cash and cards, or items in need of more clandestine transportation, they'll be safe inside this box. CNC'd from stout aluminum alloy, it uses Bluetooth to access a smartphone's biometric authentication, preventing unwanted access. In the meantime, it's designed to be unassuming while offering enough room inside for watches, rings, pipes, or anything else that needs to be hidden away.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 24,
        "preview_img_id": 71,
    },
    {
        "id": 72,
        "title": "LOVEHONEY BLOWMOTION 12 DAYS OF PLAY ADVENT CALENDAR",
        "description": "Turn the 12 days of Christmas into 12 days of pleasure with this sexy advent calendar from Lovehoney. $120.",
        "detailed_description": "Turn the 12 days of Christmas into 12 days of pleasure with this sexy advent calendar from Lovehoney. Leading the way in the box is Blowmotion's Dual-Entrance Real-Feel Vibrator, ideal for solo play. It's joined by a textured stroker, rechargeable bullet vibrator, and a host of massagers, rings, plugs, and other goodies. Overall, it offers $240 in value and can be purchased from Lovehoney, the world's biggest online retailer for all things pleasure. Until November 30th, the retailer is offering discounts of up to 60% as part of its Black Friday/Cyber Monday sale.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 12,
        "preview_img_id": 72,
    },
    {
        "id": 73,
        "title": "ASYSTEM NATURAL SUPPLEMENTS",
        "description": "Advanced supplement systems designed to help you look, feel, and perform at your best. $40+.",
        "detailed_description": "From moms, dads, athletes, and even superhero alter-egos, Asystem has a supplement for everyone. The brand's target systems offer a solution for modern lifestyles so you can look, feel, and perform at your best. Their range includes plans for creatives looking to increase productivity, travelers needing to overcome jet lag, couples longing to reconnect, and a system specifically designed for Bruce Wayne to enhance energy and combat fatigue. All of their advanced natural supplements contain powerful clinical ingredients proven to work and are formulated to help individuals satisfy their goals and needs, whether it's keeping up with their kids or the underbelly of Gotham City. 25% off products for today only during their End of Year sale with code; THANKS25.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 40,
        "preview_img_id": 73,
    },
    {
        "id": 74,
        "title": "FORME FITNESS MIRROR",
        "description": "Designer Yves Behar conceals an entire home gym within a sleek, full-length mirror. $149+.",
        "detailed_description": "The award-winning FORME Studio with Lift is the most immersive and aesthetically distinct all-in-one home gym. The Lift is a sleek, stowable add-on to the FORME Studio that allows members to enhance their strength-training experience with electromagnetic resistance cable workouts. With Lift, members can choose from a wide variety of custom trainer-designed planned sessions & self-guided workouts to do on demand. It comes equipped with 6 premium attachments that power hundreds of exercises, and accommodates up to 200lbs of smooth-pull resistance. The Lift also seamlessly integrates into FORME's Live 1:1 Personal Training service, allowing members to meet with top trainers all over the country from the comfort of their home or on-the-go with the FORME app.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 14,
        "preview_img_id": 74,
    },
    {
        "id": 75,
        "title": "MARVIS AMARELLI LICORICE MINT TOOTHPASTE",
        "description": "Marvis' licorice-mint paste thwarts the advance of tartar, plaque, cavities, and decay, and it... $11.",
        "detailed_description": "Marvis' licorice-mint paste thwarts the advance of tartar, plaque, cavities, and decay, and it leaves you with a sweet and fresh tingle that feels as refreshing as mouthwash. Think artisanal candy flavor, that's what you'll be brushing your teeth with.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 11,
        "preview_img_id": 75,
    },
    {
        "id": 76,
        "title": "INSIDETRACKER",
        "description": "The health and wellness platform uses five blood biomarkers to improve athletic performance. $49+.",
        "detailed_description": "The road to a longer, healthier life starts inside, and that's where InsideTracker starts. Founded by leading scientists in aging, genetics, and biometric data, they use a patented algorithm to analyze your body's data to provide a clear picture of what's happening inside you. Then they offer you science-backed recommendations for positive diet and lifestyle changes, give you a concrete action plan and track your progress toward reaching your goals every day, every step of the way. There's no better time to invest in your health than right now. This Black Friday and Cyber Monday, get $200 off InsideTracker's Ultimate plan and 34 percent off the entire store.",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 49,
        "preview_img_id": 76,
    },
    {
        "id": 77,
        "title": "THE NUE CO. WATER THERAPY",
        "description": "Functional fragrance relieves stress and anxiety with a marine-inspired scent. $95.",
        "detailed_description": "Inspired by blue medicine; the belief that water can have a powerful impact on our state of mind and parasympathetic nervous system, The Nue Co Water Therapy pairs sustainably sourced extracts with technology that mimics the calming sensory effect of water. The formula is created with innovative olfactory technology using specific families of volatile organic compounds found in an oceanic setting to replicate a marine environment. These compounds trigger primal protein pathways in our brain, making a neurological connection to blue spaces and recreating the feeling of calm from being near the sea. The result is a scent that blends sandalwood, seaweed, clary sage, cardamom, and fir with notes of marine salt and amber accords for a fresh and crisp fragrance with warm and woody undertones. Studies find that the scent reduces everyday stress and anxiety within thirty minutes of use and even more significantly over thirty days. Use Code UNCRATE30 to Shop 30 percent off all products including Water Therapy",
        "category_id": 7,
        "owner_id": randint(1, 3),
        "price": 95,
        "preview_img_id": 77,
    },
]


products_body_imgs = [
    {
        "id": 67,
        "product_id": 67,
        "url": "https://uncrate.com/assets_c/2022/12/daneson-every-blend-pack-1-thumb-960xauto-155376.jpg",
    },
    {
        "id": 68,
        "product_id": 68,
        "url": "https://uncrate.com/assets_c/2022/09/wayne-enterprises-patricks-trio-21-thumb-960xauto-151731.jpg",
    },
    {
        "id": 69,
        "product_id": 69,
        "url": "https://uncrate.com/assets_c/2022/12/jack-henry-balance-thumb-960xauto-155300.jpg",
    },
    {
        "id": 70,
        "product_id": 70,
        "url": "https://uncrate.com/assets_c/2022/12/quip-bundle-1-thumb-960xauto-155235.jpg",
    },
    {
        "id": 71,
        "product_id": 71,
        "url": "https://uncrate.com/assets_c/2022/12/tooletries-shower-set-1a-thumb-960xauto-155139.jpg",
    },
    {
        "id": 72,
        "product_id": 72,
        "url": "https://uncrate.com/assets_c/2022/11/blowmotion-12-advent-calendar-thumb-960xauto-154933.jpg",
    },
    {
        "id": 73,
        "product_id": 73,
        "url": "https://uncrate.com/assets_c/2022/11/asystem-natural-supplements-thumb-960xauto-154941.jpg",
    },
    {
        "id": 74,
        "product_id": 74,
        "url": "https://uncrate.com/assets_c/2020/04/forme-fitness-mirror-2-thumb-960xauto-113924.jpg",
    },
    {
        "id": 75,
        "product_id": 75,
        "url": "https://uncrate.com/assets_c/2018/08/marvis-licorice-toothpaste-1-thumb-960xauto-88018.jpg",
    },
    {
        "id": 76,
        "product_id": 76,
        "url": "https://uncrate.com/assets_c/2022/11/inside-tracker-5-thumb-960xauto-154723.jpg",
    },
    {
        "id": 77,
        "product_id": 77,
        "url": "https://uncrate.com/assets_c/2022/10/nue-co-water-therapy-thumb-960xauto-153245.jpg",
    },
]
